### ISSUE TITLE
update setup_gitignore()

### ISSUE THREAD

**Issue by tessam30** [USAID-OHA-SI/glamr#81]
Determine whether we call `usethis::git_vaccinate()` in setup function or if we just modify the existing file paths to add in .DS_Store and .httr_oauth

**Comment by baboyma** [comment]
+ duplication: list of files to be excluded is being appended regardless

Eg: clone any repo and run `glamr::si_setup()`

**Comment by achafetz** [comment]
I'd like to blame @tessam30 because he updated `glamr::si_setup()` last. I believe this used to work using `missing_section()` which searched for text within the gitignore file. Not sure what changed

https://github.com/USAID-OHA-SI/glamr/blob/1cd0eed77003ea3365966fca33272bf31dcd2a44/R/setup_project.R#L170C8-L181
